sonar.projectKey=devops-lab-app
sonar.projectName=devops-lab-app
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=node_modules/**,Jenkinsfile,*.yaml,*.yml
sonar.language=js
sonar.sourceEncoding=UTF-8
